version: '3.8'

services:
  equorn:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: equorn
    ports:
      - "3000:3000"
    volumes:
      - ./packages:/app/packages
      - ./output:/app/output
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - postgres
    networks:
      - equorn-network

  postgres:
    image: postgres:14-alpine
    container_name: equorn-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=equorn
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=loredb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - equorn-network

networks:
  equorn-network:
    driver: bridge

volumes:
  postgres-data:
